name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    clippy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                components: clippy
            - name: Install alsa and udev
              run: sudo apt-get update --fix-missing; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
            - name: Run clippy
              run: cargo clippy -- -D warnings
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
            - name: Install alsa and udev
              run: sudo apt-get update --fix-missing; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
            - name: Test
              run: cargo test